apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-shared-config
data:
  PORT: "9084"
  GRPC_WEB_PORT: "9083"
  STREAM_SERVER_PORT: "9085"
  STREAM_SERVER_WEB_PORT: "9086"
  ENV: "PROD"
  DB_URL: "user:pass@tcp(mysql:3306)/gym_reg?charset=utf8&parseTime=True&loc=Local"
  REDIS_URL: "redis://:yourpassword@redis:6379"
  RECAPTCHA_SECRET: "6LdzdyosAAAAAFHgi2co4F8CuvKDlYf_9I74aQKl"
  LCA_URI: "grpc.lcas.spider-nitt.org:443"
  CA_CERT_FILE: "/app/ca-cert.pem"
  TOKEN_EXPIRY: "86400"
  DEPLOY_SERVER: "PROD"

