apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gym-reg

resources:
  - namespace.yaml
  - gateway.yaml
  - virtualservice-frontend.yaml
  - virtualservice-admin.yaml
  - virtualservice-backend.yaml
  - destinationrule-frontend.yaml
  - destinationrule-admin.yaml
  - destinationrule-backend.yaml
  - destinationrule-databases.yaml
  - peer-authentication.yaml
  - authorization-policy.yaml
  - sidecar.yaml
  - service-entry.yaml
  - telemetry.yaml
