apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gym-reg-ingress-grpc
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  rules:
  - http:
      paths:
      - path: /api/main(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: backend-main
            port:
              number: 9083
      - path: /api/stream(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: backend-stream
            port:
              number: 9086
