apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-panel-config
  labels:
    app: admin-panel
data:
  NEXT_PUBLIC_SITE_KEY: "6LdzdyosAAAAAMzfm3vzEH8DGd6lAX2sWYHBFvTh"
  NEXT_PUBLIC_HOST: "http://localhost:9083"
  NEXT_PUBLIC_HOST_STREAM: "http://localhost:9086"
  NODE_ENV: "production"
  PORT: "3001"
