apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-panel-config
  labels:
    app: admin-panel
data:
  NEXT_PUBLIC_SITE_KEY: "6Lf8xCwsAAAAALdb6EZK71zT09OEdhU5RmX-_6Pk"
  NEXT_PUBLIC_HOST: "/api/main"
  NEXT_PUBLIC_HOST_STREAM: "/api/stream"
  BASE_PATH: "/admin"
  NODE_ENV: "production"
  PORT: "3001"
