name: Minikube Matrix CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  minikube-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8s_version: ["1.29.14", "1.30.13", "1.31.14", "1.32.11", "1.33.7", "1.34.3"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Minikube
        uses: medyagh/setup-minikube@v0.0.20
        with:
          kubernetes-version: ${{ matrix.k8s_version }}
          driver: docker

      - name: Verify kubectl version
        run: |
          kubectl version --client && kubectl version

      - name: Run CI tests
        run: |
          ./tests/ci-test.sh
